# Generated by Django 5.1.4 on 2025-01-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="extra",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
