# Generated by Django 5.1.4 on 2025-02-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_added_extra_field_to_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessage',
            name='send_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
