all:
  hosts:
    intbot_setup:
      ansible_host: internal.europython.eu
      ansible_user: root
      nginx_user: nginx_user
      app_user: intbot_user

    intbot_nginx:
      ansible_host: internal.europython.eu
      ansible_user: nginx_user
      app_user: intbot_user
      domain_name: internal.europython.eu
      app_port: 4672
      letsencrypt_email: "infra+leinternal@europython.eu"
      letsencrypt_rsa_key_size: 4096

    intbot_app:
      ansible_host: internal.europython.eu
      ansible_user: intbot_user
      app_port: 4672
      repository_url: git@github.com:europython/internal-bot.git
