- name: Deploy the bot/app/worker on remote host
  hosts: intbot_app

  tasks:
    - name: Clone the repository to a specific version (to a temp location)
      ansible.builtin.git:
        repo: "{{ repository_url }}"
        dest: /tmp/src
        accept_hostkey: true
        version: "{{ app_version }}"

    - name: Build with a given commit hash
      # This will be stored in local registry, and available as version to docker-compose
      # where we can just reference correct version
      ansible.builtin.shell: 
        chdir: /tmp/src
        cmd: "/usr/bin/make docker/build V={{ app_version }}"

    - name: Create a server Makefile to manage app tasks
      ansible.builtin.template:
        src: app/Makefile.app.j2
        dest: ./Makefile
        mode: "0640"

    - name: Set up docker-compose.yml for the app
      ansible.builtin.template:
        src: app/docker-compose.app.yml.j2
        dest: ./docker-compose.yml
        mode: "0640"

    - name: Copy env file example
      ansible.builtin.copy:
        src: ../templates/app/intbot.env.example
        dest: intbot.env.example

    - name: Check if the env file exists
      ansible.builtin.stat:
        path: intbot.env
      register: env_file

    - name: If env file doesn't exist - copy the example
      ansible.builtin.copy:
        src: app/intbot.env.example
        dest: intbot.env.example
        mode: "0644"
      when: not env_file.stat.exists

    - name: If the env file doesn't exist - fail with error message
      ansible.builtin.fail:
        msg: "The env file doesn't exist. Please ssh, copy the example and adjust"
      when: not env_file.stat.exists

    - name: Start docker compose to see if everything is running
      ansible.builtin.command:
        chdir: {{ ansible_user_dir }}
        cmd: "docker compose up -d"

    - name: Migrate on prod
      ansible.builtin.shell: 
        chdir: /tmp/src
        cmd: "/usr/bin/make prod/migrate"

    - name: Restart everything and finish
      ansible.builtin.command:
        chdir: {{ ansible_user_dir }}
        cmd: "docker compose up -d"
