- name: Scheduled tasks using the bot user
  hosts: intbot_app

  tasks:
    - name: "Wipe user's crontab"
      command: crontab -r

    - name: "Download pretalx data once a day"
      ansible.builtin.cron:
        name: "Download pretalx data once a day at 06:05am"
        minute: "5"
        hour: "6"
        job: "make prod/cron/pretalx"

    - name: "Download pretix data once a day"
      ansible.builtin.cron:
        name: "Download pretix data once a day at 07:05am"
        minute: "5"
        hour: "7"
        job: "make prod/cron/pretix"

    - name: "Schedule standup message on Monday morning"
      ansible.builtin.cron:
        name: "Send a standup message"
        minute: "5"
        hour: "9"
        weekday: "1"
        job: "make prod/cron/standup"
