- name: Scheduled tasks using the bot user
  hosts: intbot_app

  tasks:
    - name: "Download pretalx data every hour"
      ansible.builtin.cron:
        name: "Download pretalx data every hour"
        minute: "5"
        hour: "8"     # run once a day at 08:05 am
        job: "make prod/cron/pretalx"
