- name: Scheduled tasks using the bot user
  hosts: intbot_app

  tasks:
    - name: "Download pretalx data every hour"
      ansible.builtin.cron:
        name: "Download pretalx data every hour"
        minute: "5"   # run on the 5th minute of every hour
        job: "make prod/cron/pretalx"
