- name: Scheduled tasks using the bot user
  hosts: intbot_app

  tasks:
    - name: "Download pretalx data every hour"
      ansible.builtin.cron:
        name: "Download pretalx data once a day at 05:05am"
        minute: "5"
        hour: "5"     # run once a day at 08:05 am
        job: "make prod/cron/pretalx"

      ansible.builtin.cron:
        name: "Download pretix data once a day at 06:05am"
        minute: "5"
        hour: "6"
        job: "make prod/cron/pretix"
